### ISSUE TITLE
resume_path

### ISSUE THREAD

**Issue by HeliaHashemipour** [shijianjian/DIA#3]
Another problem is in the resume path which has an error :

=> Loading checkpoint from '/content/drive/MyDrive/BS.c_project/DIA/logs/pneumoniamnist_resnet18_unsup_simclr_DIA_shift_DIA_diffusion_rotation_res32_one_class_0'
Traceback (most recent call last):
  File "/content/drive/MyDrive/BS.c_project/DIA/train.py", line 6, in <module>
    from common.train import *
  File "/content/drive/MyDrive/BS.c_project/DIA/common/train.py", line 132, in <module>
    best = config['best']
KeyError: 'best'

**Comment by shijianjian** [comment]
I may fix this one later. I never tried to resume previously XD
